@echo off
echo Starting Git auto push program...
echo Please make sure you run this script as administrator.
echo Switching to git_auto_push directory and running the program...
cd /d "%~dp0git_auto_push"
echo Running git_auto_push.exe...
git_auto_push.exe
echo.
echo Program execution completed.
echo Press any key to exit...
pause >nul